# Generated by Django 3.1 on 2020-08-26 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sqrt',
            new_name='sqft',
        ),
    ]
